import React, {useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Conversation} from './src/features/conversation/Conversation';
import {PlanPane} from './src/features/plan/PlanPane';
import {makePlan, makeView} from './src/test-support/fixtures';
import {emptySession} from './src/transport/session';
import './src/styles.css';
const plan=makePlan({workflow:'PANDA',status:'ready',objective:'Infer the aggregate transcription factor–gene regulatory network.',decision:{action:'run_panda',precision:'double',computing:'cpu',mode_process:'intersection'},evidence:[{field:'expression_file',value:'data/study/expression.tsv',status:'provided',reason:'Provided by user',candidates:[],candidate_bundle_ids:[],bundle_id:null},{field:'motif_file',value:'data/study/motif.tsv',status:'provided',reason:'Provided by user',candidates:[],candidate_bundle_ids:[],bundle_id:null},{field:'ppi_file',value:'data/study/ppi.tsv',status:'provided',reason:'Provided by user',candidates:[],candidate_bundle_ids:[],bundle_id:null},{field:'output_file',value:'outputs/sessions/audit/panda.tsv',status:'defaulted',reason:'Session default',candidates:[],candidate_bundle_ids:[],bundle_id:null}],steps:[{action:'inspect_inputs',purpose:'Validate identifiers and matrix formats.',arguments:{}},{action:'run_panda',purpose:'Infer the aggregate network.',arguments:{precision:'double',mode_process:'intersection'}}]});
function Audit(){const [connection,setConnection]=useState('reconnecting');const [prompt,setPrompt]=useState('main');const [submitted,setSubmitted]=useState('');const view=makeView({prompt_kind:prompt as any,plan,plan_hash:'0123456789abcdef',text:prompt==='clarification'?'Please provide the expression matrix.':'' ,target_field:prompt==='clarification'?'expression_file':null});const session={...emptySession('audit-fixture'),connection:connection as any,view,entries:[],busy:false};return <><div style={{padding:12,background:'#fff4ce',color:'#222'}}>AUDIT FIXTURE — actual React components with synthetic props; no daemon or LLM connected. <label>Connection <select value={connection} onChange={e=>setConnection(e.target.value)}><option>reconnecting</option><option>open</option></select></label> <label>State <select value={prompt} onChange={e=>setPrompt(e.target.value)}><option>main</option><option>clarification</option><option>execution_confirmation</option></select></label><span> Last callback: {submitted||'none'}</span></div><div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 340px',height:'calc(100vh - 90px)'}}><Conversation session={session} onAnswer={setSubmitted} onSlash={setSubmitted} onApprove={()=>setSubmitted('APPROVAL ACCEPTED')} onDecline={()=>setSubmitted('decline')} onCancel={()=>setSubmitted('cancel')}/><PlanPane plan={plan} hash={view.plan_hash}/></div><footer className="statusbar">{connection==='reconnecting'?'Reconnecting…':'Connected'}</footer></>};createRoot(document.getElementById('root')!).render(<Audit/>);
